Update nodes.py
precice-forschungsprojekt/config-graph pull request #19
Opened 2024-12-21 11:33 UTC by orlandoisepic

Implemented new node types

2024-12-21 11:34 UTC, orlandoisepic commented
This should cover the nodes, but for now edges are still missing

2025-01-08 11:25 UTC, s3n-w6i commented on precice_config_graph/edges.py
> +    MULTI_COUPLING_SCHEME__PARTICIPANT_CONTROL = "multi_coupling_scheme-participant_control"
```suggestion
    MULTI_COUPLING_SCHEME__PARTICIPANT_CONTROL = "multi-coupling-scheme_participant-control"
```

2025-01-08 11:31 UTC, s3n-w6i commented on precice_config_graph/edges.py
> +    MULTI_COUPLING_SCHEME__PARTICIPANT_REGULAR = "multi_coupling_scheme-participant_regular"
```suggestion
    MULTI_COUPLING_SCHEME__PARTICIPANT_REGULAR = "multi-coupling-scheme_participant-regular"
```

2025-01-08 11:58 UTC, s3n-w6i requested changes
Good base, some changes are still needed

2025-01-08 11:58 UTC, s3n-w6i commented on precice_config_graph/edges.py
> +    ACTION_PARTICIPANT = "action-participant"
```suggestion
    ACTION_PARTICIPANT = "action_participant"
```

2025-01-08 11:58 UTC, s3n-w6i commented on precice_config_graph/edges.py
> +    ACTION_MESH = "action-mesh"
```suggestion
    ACTION_MESH = "action_mesh"
```

2025-01-08 11:58 UTC, s3n-w6i commented on precice_config_graph/edges.py
> +    ACTION_DATA = "action-data"
```suggestion
    ACTION_DATA = "action_data"
```

2025-01-08 11:58 UTC, s3n-w6i commented on precice_config_graph/edges.py
> +    WATCHPOINT_PARTICIPANT = "watchpoint-participant"
```suggestion
    WATCHPOINT_PARTICIPANT = "watchpoint_participant"
```

2025-01-08 11:58 UTC, s3n-w6i commented on precice_config_graph/edges.py
> +    WATCHPOINT_MESH = "watchpoint-mesh"
```suggestion
    WATCHPOINT_MESH = "watchpoint_mesh"
```

2025-01-08 11:58 UTC, s3n-w6i commented on precice_config_graph/edges.py
> +    WATCHINTEGRAL_PARTICIPANT = "watchintegral-participant"
```suggestion
    WATCHINTEGRAL_PARTICIPANT = "watchintegral_participant"
```

2025-01-08 11:58 UTC, s3n-w6i commented on precice_config_graph/edges.py
> +    WATCHINTEGRAL_MESH = "watchintegral-mesh"
```suggestion
    WATCHINTEGRAL_MESH = "watchintegral_mesh"
```

2025-01-08 11:58 UTC, s3n-w6i commented on precice_config_graph/edges.py
> +    PARTICIPANT_EXPORT = "participant-export"
```suggestion
    EXPORT__CHILD_OF = "export_child-of"
```
to be in line with, for example, `read-data`. If we are to switch to undirected edges, then this would probably not be needed.

2025-01-08 11:58 UTC, s3n-w6i commented on precice_config_graph/edges.py
> +    DATA_EXPORT = "data-export"
export node does not have a data attribute
```suggestion
```

2025-01-08 11:58 UTC, s3n-w6i commented on precice_config_graph/nodes.py
> +
unused extra line
```suggestion
```

2025-01-08 11:58 UTC, s3n-w6i commented on precice_config_graph/nodes.py
> +            self.mappings = mappings
would have been happy if this was more compact, but hey… not a big issue.

2025-01-08 11:58 UTC, s3n-w6i commented on precice_config_graph/nodes.py
> +        # TODO control participant as first entry of participants[] ?
No, this just makes it overly complex to mentally map the original config to the generated graph.

2025-01-08 11:58 UTC, s3n-w6i commented on precice_config_graph/nodes.py
> +#  as it is not used/connectd to anything else
Would just skip that entirely. It does not make sense to have that in the graph.

2025-01-08 11:58 UTC, s3n-w6i commented on precice_config_graph/nodes.py
> +            self.mesh = mesh
```suggestion
        self.mesh = mesh
```
this cumbersome workaround is only needed for lists!

2025-01-08 11:58 UTC, s3n-w6i commented on precice_config_graph/nodes.py
> +            self.mesh = mesh
```suggestion
        self.mesh = mesh
```
see comment above

2025-01-08 11:58 UTC, s3n-w6i commented on precice_config_graph/nodes.py
> +            self.mesh = mesh
```suggestion
        self.mesh = mesh
```
see comment above

2025-01-08 12:00 UTC, orlandoisepic commented on precice_config_graph/nodes.py
> +        # TODO control participant as first entry of participants[] ?
That's also what I thought. Thanks

2025-01-08 12:01 UTC, orlandoisepic commented on precice_config_graph/nodes.py
> +#  as it is not used/connectd to anything else
Yup

2025-01-08 12:02 UTC, orlandoisepic commented on precice_config_graph/nodes.py
> +            self.mesh = mesh
oh

2025-01-08 12:04 UTC, orlandoisepic commented on precice_config_graph/nodes.py
> +            self.mappings = mappings
according to pep8, this is the correct formatting

2025-01-08 12:05 UTC, s3n-w6i approved these changes
Lfg 🚀

2025-01-08 12:06 UTC, merged